// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: proto/Addition.proto

package addition

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Num1          int32                  `protobuf:"varint,1,opt,name=num1,proto3" json:"num1,omitempty"`
	Num2          int32                  `protobuf:"varint,2,opt,name=num2,proto3" json:"num2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRequest) Reset() {
	*x = AddRequest{}
	mi := &file_proto_Addition_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRequest) ProtoMessage() {}

func (x *AddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Addition_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRequest.ProtoReflect.Descriptor instead.
func (*AddRequest) Descriptor() ([]byte, []int) {
	return file_proto_Addition_proto_rawDescGZIP(), []int{0}
}

func (x *AddRequest) GetNum1() int32 {
	if x != nil {
		return x.Num1
	}
	return 0
}

func (x *AddRequest) GetNum2() int32 {
	if x != nil {
		return x.Num2
	}
	return 0
}

type AddResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int64                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddResponse) Reset() {
	*x = AddResponse{}
	mi := &file_proto_Addition_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddResponse) ProtoMessage() {}

func (x *AddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Addition_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddResponse.ProtoReflect.Descriptor instead.
func (*AddResponse) Descriptor() ([]byte, []int) {
	return file_proto_Addition_proto_rawDescGZIP(), []int{1}
}

func (x *AddResponse) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_proto_Addition_proto protoreflect.FileDescriptor

const file_proto_Addition_proto_rawDesc = "" +
	"\n" +
	"\x14proto/Addition.proto\x12\baddition\"4\n" +
	"\n" +
	"AddRequest\x12\x12\n" +
	"\x04num1\x18\x01 \x01(\x05R\x04num1\x12\x12\n" +
	"\x04num2\x18\x02 \x01(\x05R\x04num2\"%\n" +
	"\vAddResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x03R\x06result2E\n" +
	"\x0fadditionService\x122\n" +
	"\x03Add\x12\x14.addition.AddRequest\x1a\x15.addition.AddResponseB\fZ\n" +
	"./additionb\x06proto3"

var (
	file_proto_Addition_proto_rawDescOnce sync.Once
	file_proto_Addition_proto_rawDescData []byte
)

func file_proto_Addition_proto_rawDescGZIP() []byte {
	file_proto_Addition_proto_rawDescOnce.Do(func() {
		file_proto_Addition_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_Addition_proto_rawDesc), len(file_proto_Addition_proto_rawDesc)))
	})
	return file_proto_Addition_proto_rawDescData
}

var file_proto_Addition_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_Addition_proto_goTypes = []any{
	(*AddRequest)(nil),  // 0: addition.AddRequest
	(*AddResponse)(nil), // 1: addition.AddResponse
}
var file_proto_Addition_proto_depIdxs = []int32{
	0, // 0: addition.additionService.Add:input_type -> addition.AddRequest
	1, // 1: addition.additionService.Add:output_type -> addition.AddResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_Addition_proto_init() }
func file_proto_Addition_proto_init() {
	if File_proto_Addition_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_Addition_proto_rawDesc), len(file_proto_Addition_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_Addition_proto_goTypes,
		DependencyIndexes: file_proto_Addition_proto_depIdxs,
		MessageInfos:      file_proto_Addition_proto_msgTypes,
	}.Build()
	File_proto_Addition_proto = out.File
	file_proto_Addition_proto_goTypes = nil
	file_proto_Addition_proto_depIdxs = nil
}
