global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s

  - job_name: 'service-a'
    static_configs:
      - targets: ['service-a:8081']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'service-b'
    static_configs:
      - targets: ['service-b:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s